### ISSUE TITLE
Empty MQTT URI causes Boot Loop

### ISSUE THREAD

**Issue by dylanh117** [G-Two/smoke-x-receiver#13]
By applying MQTT config with an empty URI field, the device is stuck in a boot loop. Re-flashing will not recover it

**Comment by dylanh117** [comment]
I was able to resolve this by clearing the NVS partition using the following: `$ esptool.py erase_region 0x9000 0x6000`

**Comment by G-Two** [comment]
Reopening this because the bug hasn't been fixed in the code yet.

**Comment by G-Two** [comment]
It has now been fixed with 2b679c0b280c4549b3d26dc924d67ebedb305612
