### ISSUE TITLE
MQTT_CLIENT: SSL related configs set, but the URI scheme specifies a non-SSL scheme

### ISSUE THREAD

**Issue by dylanh117** [G-Two/smoke-x-receiver#14]
Getting the above error message when trying to configure MQTT. I deselected "Enable MQTT over SSL" under component config -> ESP-MQTT in menuconfig.

The workaround I used was to remove `.cert_pem = app_mqtt_params.ca_cert` from line 260 of `./main/app_mqtt.c`, then re-build & flash.

**Comment by G-Two** [comment]
This is now fixed in 2b679c0b280c4549b3d26dc924d67ebedb305612
